import{jsx as s,jsxs as m}from"react/jsx-runtime";import{useState as G,useRef as k,useMemo as y}from"react";import{useTranslation as M}from"react-i18next";import I from"../../components/ui/Button";import z from"../../components/ui/TextArea";function L(){const{t:f}=M(),u=k(null),[x,N]=G(`Root
  Child 1
    Grandchild 1.1
    Grandchild 1.2
  Child 2
    Grandchild 2.1`),g=y(()=>{const e=x.split(`
`).filter(r=>r.trim());if(e.length===0)return null;const n={name:"Root",children:[]},l=[];e.forEach((r,d)=>{const i=r.trim(),a=r.search(/\S/)/2,h={name:i,children:[]};if(d===0){l.push({node:h,level:a});return}for(;l.length>0&&l[l.length-1].level>=a;)l.pop();l.length>0&&l[l.length-1].node.children.push(h),l.push({node:h,level:a})});const c=[],t=[];return e.forEach(r=>{const d=r.trim(),i=Math.floor((r.length-r.trimLeft().length)/2),a={name:d,children:[]};if(i===0)c.push(a),t.length=0,t.push({node:a,level:i});else{for(;t.length>0&&t[t.length-1].level>=i;)t.pop();t.length>0&&t[t.length-1].node.children.push(a),t.push({node:a,level:i})}}),c.length>0?c[0]:null},[x]),T=e=>{if(!e)return{nodes:[],links:[],width:0,height:0};const n=120,l=40,c=50,t=60,r=[],d=[];let i=0;const a=(o,b)=>{if(o.children.length===0)o.y=i,i+=t;else{o.children.forEach(R=>a(R,b+1));const p=o.children[0],E=o.children[o.children.length-1];o.y=(p.y+E.y)/2}o.x=b*(n+c)+50,r.push({...o,id:Math.random()}),o.children.forEach(p=>{d.push({source:o,target:p})})};a(e,0);const h=i+t,D=Math.max(...r.map(o=>o.x))+n+50;return{nodes:r,links:d,width:D,height:h}},{nodes:C,links:$,width:v,height:w}=y(()=>T(g),[g]),S=()=>{if(!u.current)return;const e=new XMLSerializer().serializeToString(u.current),n=document.createElement("canvas"),l=n.getContext("2d"),c=new Image;n.width=v,n.height=w,c.onload=()=>{if(l){l.fillStyle="white",l.fillRect(0,0,n.width,n.height),l.drawImage(c,0,0);const t=document.createElement("a");t.download="tree-diagram.png",t.href=n.toDataURL("image/png"),t.click()}},c.src="data:image/svg+xml;base64,"+btoa(unescape(encodeURIComponent(e)))};return m("div",{className:"flex flex-col md:flex-row gap-6 h-[calc(100vh-200px)] min-h-[600px]",children:[s("div",{className:"w-full md:w-1/3 flex flex-col gap-4",children:m("div",{className:"bg-white p-4 rounded-lg border border-slate-200 shadow-sm flex-1 flex flex-col",children:[s("h3",{className:"font-semibold text-slate-700 mb-2",children:f("tools.treeDiagram.input")}),s("p",{className:"text-xs text-slate-500 mb-2",children:f("tools.treeDiagram.hint")}),s(z,{value:x,onChange:e=>N(e.target.value),className:"flex-1 font-mono text-sm",placeholder:`Root
  Child 1
    Grandchild`})]})}),m("div",{className:"flex-1 bg-white rounded-lg border border-slate-200 shadow-sm flex flex-col overflow-hidden",children:[s("div",{className:"p-2 border-b border-slate-100 flex justify-end bg-slate-50",children:s(I,{variant:"secondary",onClick:S,disabled:!g,children:f("common.download")})}),s("div",{className:"flex-1 overflow-auto p-4",children:g?s("svg",{ref:u,width:v,height:w,className:"min-w-full min-h-full",children:m("g",{children:[$.map((e,n)=>s("path",{d:`M${e.source.x+120},${e.source.y+20} 
                       C${e.source.x+120+50},${e.source.y+20} 
                        ${e.target.x-50},${e.target.y+20} 
                        ${e.target.x},${e.target.y+20}`,fill:"none",stroke:"#cbd5e1",strokeWidth:"2"},n)),C.map((e,n)=>m("g",{transform:`translate(${e.x}, ${e.y})`,children:[s("rect",{width:"120",height:"40",rx:"6",fill:"#eff6ff",stroke:"#3b82f6",strokeWidth:"1"}),s("text",{x:"60",y:"20",dy:"0.3em",textAnchor:"middle",className:"text-xs font-medium fill-slate-700",style:{fontSize:"12px"},children:e.name.length>15?e.name.substring(0,14)+"...":e.name})]},n))]})}):s("div",{className:"flex items-center justify-center h-full text-slate-400",children:f("tools.treeDiagram.empty")})})]})]})}export{L as default};
